#!/usr/bin/env bash
# Display information about subdomains

subdomain_info() {
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi
	for sub in "${subdomains[@]}"; do
		record_type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2{print $4}')
		destination=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2{print $5}')
		echo "The subdomain $sub.$domain is a $record_type record and points to $destination"
	done
}

if [ $# -lt 1 ]; then
	echo "Usage: $0 domain [subdomain]"
	exit 1
fi

domain="$1"
subdomain="$2"

subdomain_info "$domain" "$subdomain"
