#!/usr/bin/env bash
# This script configures nginx server to redirecte to another page
sudo apt-get update
sudo apt-get -y install nginx

echo "server {
		listen 80;
		server_name localhost;
		location /redirect_me {
			return 301 https://www.youtube.com/watch?v=XqZsoesa55w;
		}
}" > /etc/nginx/sites-available/redirect_me

sudo service nginx start
