#!/usr/bin/env bash
# This script configures nginx server to to have a 404 page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's/location \/ {/location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=XqZsoesa55w;/' /etc/nginx/sites-available/default
sudo sh -c 'echo "location @404 { return 404 "Ceci n'\''est pas une page";}" >> /etc/nginx/sites-available/default'

sudo nginx -t
sudo service nginx restart
