#!/usr/bin/env bash
# This script installs haproxy and configures it using roundrobin algorithm

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

echo -e "frontend http\n\tbind *:80\n\tdefault_backend myservers\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo -e "backend myservers\n\tbalance roundrobin\n\tserver 370337-web-01 52.86.213.205:80 check\n\tserver 370337-web-02 52.91.119.144:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
